name: Test library

on: [push, pull_request]

jobs:
    test-library:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python:
                    - { name: "CPython 3.9", version: "3.9", env: "py39" }
                    - { name: "CPython 3.10", version: "3.10", env: "py310" }
                    - { name: "CPython 3.11", version: "3.11.0-rc.2", env: "py311" }
                    - { name: "PyPy 3.9", version: "pypy3.9", env: "pypy39" }

        steps:
            - uses: actions/checkout@v3

            - name: Setup ${{ matrix.python.name }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python.version }}

            - name: Install tox
              run: pipx install tox

            - name: Test with tox
              run: tox -e ${{ matrix.python.env }}

    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install tox
              run: pipx install tox

            - name: Test and report coverage
              run: tox -e coverage

            - name: Upload coverage
              uses: codecov/codecov-action@v3
